version: '3.4'

services:
  raketechchallenge:
    image: raketechchallenge
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8081:80
